import Head from "next/head";
import styles from "../../../../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import axios from "../lib/axios";

import Card from '@mui/material/Card'

export default function Home() {
    const router = useRouter();

    const handlePrev = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      router.push('/home/components/other');
    };

  return (
    <Card>
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}  onSubmit={(event) => {event.preventDefault()}}>
              <div className={`${styles.formHeader}`}>
                <h2>Form Preview</h2>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handlePrev} className={`${styles.formBtn}`}>Previous</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
    </Card>
  );
}
