import Head from "next/head";
import styles from "../../../../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import { TextField } from "@mui/material";
import axios from "../lib/axios";

import Card from '@mui/material/Card'

export default function Home() {
    const router = useRouter();

  const [dataFetched, setDataFetched] = useState(false);
  const [otherInfo, setOtherInfo] = useState({registrationNo:'1', foodHabit: '', laptopDetails: '', modelNumber: '', serialNumber: '', emailUsername: '', emailPassword: '', bankName: '', accountNumber: '', confirmAccountNumber: '', IFSCCode: ''});

    const handleInputChange = (event) => {
      const { id, value } = event.target;
      const obj = {...otherInfo};
      obj[id] = value;
      setOtherInfo(Object.assign({}, obj));
      localStorage.setItem('otherInfo', JSON.stringify(otherInfo));
      console.log(id, otherInfo[id]);
    };
  
    const handleInputChangeByName = (event) => {
      const { name, value } = event.target;
      const obj = {...otherInfo};
      obj[name] = value;
      setOtherInfo(Object.assign({}, obj));
      localStorage.setItem('otherInfo', JSON.stringify(otherInfo));
      console.log(name, otherInfo[name]);
    };

    const getInfo = async () => {
      const response = await axios.get('/api/OtherInfo/1');
      console.log(response.status, response.data);
      setOtherInfo(response.data);
    }
  
    if(!dataFetched){
      getInfo();
      setDataFetched(true);
    }

    const postInfo = async () => {
      console.log(otherInfo);
      console.log(localStorage.otherInfo);
      const response = await axios.post('/api/postOtherInfo', {data:otherInfo});
      console.log(response.status, response.data);
      return (response.status === 200 || response.status === 201);
    }

    const handlePrev = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
    if(postInfo()) {
      router.push('/home/components/parent-account');
    }
    };
  
    const handleNext = async () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      // console.log(otherInfo);
      // console.log(localStorage.otherInfo);
      // const response = await axios.post('/api/postOtherInfo', {data:otherInfo});
      // console.log(response.status, response.data);
      // router.push('/form-preview');

      if(postInfo()) {
        router.push('/home/components/form-preview');
      }
    };

  return (
    <Card>
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`} onSubmit={(event) => {event.preventDefault()}}>

            <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Important Information for Hostel</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='foodHabit' 
                    label="Food Habit"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.foodHabit}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='laptopDetails' 
                    label="If Having Laptop (Give Details)"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.laptopDetails}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='modelNumber' 
                    label="Model Number"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.modelNumber}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='serialNumber' 
                    label="Serial Number"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.serialNumber}
                    required
                  />
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Email Registraion</h3>
                  <p>(Your email will be created on IITISM Domain, adm_no@iitism.ac.in)</p>
                  <p>Your default temporary password is shown in the form. All official communication will be sent on this email only.</p>
                </div>

                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='emailUsername' 
                    label="Email Username"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.emailUsername}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='emailPassword' 
                    label="Email Password"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.emailPassword}
                    required
                  />
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Student Account Detail</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='bankName' 
                    label="Bank Name"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.bankName}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='accountNumber' 
                    label="Account Number"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.accountNumber}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='confirmAccountNumber' 
                    label="Confirm Account Number"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.confirmAccountNumber}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='IFSCCode' 
                    label="IFSC Code"
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={otherInfo.IFSCCode}
                    required
                  />
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handlePrev} className={`${styles.formBtn}`}>Previous</button>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
    </Card>
  );
}
