import Head from "next/head";
import styles from "../../../../styles/Home.module.css";
import { useState } from "react";
import { useOnce } from 'react';
import { useRouter } from "next/router";
import TextField from '@mui/material/TextField'
import dayjs from 'dayjs';
import 'dayjs/locale/en-gb';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import Radio from '@mui/material/Radio'
import RadioGroup from '@mui/material/RadioGroup'
import FormControl from '@mui/material/FormControl'
import FormControlLabel from '@mui/material/FormControlLabel'
import FormLabel from '@mui/material/FormLabel';
import Select from '@mui/material/Select';
import MenuItem from '@mui/material/MenuItem';
import InputLabel from '@mui/material/InputLabel';
import axios from "../lib/axios";
import moment from 'moment';

import Card from '@mui/material/Card'

export default function Home() {
  const router = useRouter();
  moment().format();

  const [locale, setLocale] = useState('en-gb')
  const [dataFetched, setDataFetched] = useState(false);
  const [personalInfo, setPersonalInfo] = useState({registrationNo: '1', instituteName: '', name: '', email: '', contactNo: '', gender: '', category: '', nationality: '', divyang: '', permanentAddress: '', streetLocality: '', city: '', state: '', pincode: '', country: '', dob: null, maritalStatus: '', religion: '', bloodGroup: '', kashmiriImmigrant: '', nameInHindi: '', birthPlace: '', identificationMark: '', hobbies: '', extraCurricularActivities: '', otherReleventInfo: '', parentsBankName: '', parentsAccountNo: '', parentsIFSCCode: '', candidatesFavouritePastTime: '', identityType: '', migrationCertificateNo: ''});

  const handleInputChange = (event) => {
    event.preventDefault();
    const { id, value } = event.target;
    const obj = {...personalInfo};
    obj[id] = value;
    setPersonalInfo(Object.assign({}, obj));
    localStorage.setItem('personalInfo', JSON.stringify(personalInfo));
    console.log(id, personalInfo[id]);
  };

  const handleInputChangeByName = (event) => {
    event.preventDefault();
    const { name, value } = event.target;
    const obj = {...personalInfo};
    obj[name] = value;
    setPersonalInfo(Object.assign({}, obj));
    localStorage.setItem('personalInfo', JSON.stringify(personalInfo));
    console.log(name, personalInfo[name]);
  };

  const getInfo = async () => {
    const response = await axios.get('/api/PersonalInfo/1');
    console.log(response.status, response.data);
    setPersonalInfo({...response.data, dob: null});
  }

  if(!dataFetched){
    getInfo();
    setDataFetched(true);
  }

  const postInfo = async () => {
    console.log(personalInfo);
    console.log(localStorage.personalInfo);
    const response = await axios.post('/api/postPersonalInfo', {data:personalInfo});
    console.log(response.status, response.data);
    return (response.status === 200 || response.status === 201);
  }


  const handleNext = async () => {
    // router.push('/education');
    // console.log(personalInfo);
    // console.log(localStorage.personalInfo);
    // const response = await axios.post('/api/postPersonalInfo', {data:personalInfo});
    // // const response = await axios.get('/api/PersonalInfo/1');
    // // setPersonalInfo(response.data);
    // console.log(response.status, response.data);

    if(postInfo()) {
      router.push('/home/components/education');
    }
  };

  return (
    <Card>
    <> 
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`} onSubmit={(event)=>{event.preventDefault()}}>
              <div className={`${styles.formHeader}`}>
                <h2>Personal Details</h2>
                <p>Please do not use Autofill.</p>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <TextField 
                    id='registrationNo' 
                    label='Registration Number' 
                    className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.registrationNo}
                    required
                  />
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='instituteName' label='Institute Name' className={`${styles.input}`}  
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.instituteName} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='name' label='Name' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.name} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='email' label='Email' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.email} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='contactNo' label='Contact Number' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.contactNo} required/>
                </div>
                <div className={`${styles.formBlock} ${styles.radioContainer}`}>
                  <FormControl className={`${styles.input} ${styles.radioInput} flex-wrap flex-row`}>
                    <FormLabel className={`${styles.radioLabel}`}>Gender:</FormLabel>
                    <RadioGroup row id="gender" name='gender' aria-label='gender' onChange={(event)=>handleInputChangeByName(event)} value={personalInfo.gender}>
                      <FormControlLabel value='male' control={<Radio />} label='Male' />
                      <FormControlLabel value='female' control={<Radio />} label='Female' />
                      <FormControlLabel value='transgender' control={<Radio />} label='Transgender' />
                    </RadioGroup>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='category' label='Category' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.category} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <TextField id='nationality' label='Nationality' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.nationality} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <FormControl className={`${styles.input} ${styles.radioInput} flex-wrap flex-row`}>
                    <FormLabel className={`${styles.radioLabel}`}>Divyang:</FormLabel>
                    <RadioGroup row id="divyang" name='divyang' aria-label='divyang' onChange={(event)=>handleInputChangeByName(event)} value={personalInfo.divyang}>
                      <FormControlLabel value='1' control={<Radio />} label='Yes' />
                      <FormControlLabel value='0' control={<Radio />} label='No' />
                    </RadioGroup>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='permanentAddress' label='Permanent Address' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.permanentAddress} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='streetLocality' label='Street/Locality' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.streetLocality} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='city' label='City' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.city} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='state' label='State' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.state} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='pincode' label='Pincode' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.pincode} required/>

                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='country' label='Country' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.country} required/>

                </div>
                <div className={`${styles.formBlock}`}>
                  <LocalizationProvider dateAdapter={AdapterDayjs}  adapterLocale={locale}>
                    <DatePicker id='dob' label='Date of Birth' className={`${styles.input}`} 
                    // onChange={(newValue)=>{setPersonalInfo({...personalInfo, dob: newValue}); console.log(newValue, personalInfo.dob)}} value={moment(personalInfo.dob)} 
                    />
                  </LocalizationProvider>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                <FormControl className={`${styles.input} ${styles.radioInput} flex-wrap flex-row`}>
                    <FormLabel className={`${styles.radioLabel}`}>Marital Status:</FormLabel>
                    <RadioGroup row id="maritalStatus" name='maritalStatus' aria-label='maritalStatus' onChange={(event)=>handleInputChangeByName(event)} value={personalInfo.maritalStatus}>
                      <FormControlLabel value='1' control={<Radio />} label='Married' />
                      <FormControlLabel value='0' control={<Radio />} label='Unmarried' />
                    </RadioGroup>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                  <FormControl fullWidth>
                    <InputLabel id='religion-label'>Religion</InputLabel>
                    <Select label='religion' defaultValue='' id='religion' name='religion' labelId='religion-label' onChange={(event)=>{handleInputChangeByName(event)}} value={personalInfo.religion} required>
                      <MenuItem value='' disabled>None</MenuItem>
                      <MenuItem value="hindu">Hindu</MenuItem>
                      <MenuItem value="sikh">Sikh</MenuItem>
                      <MenuItem value="christian">Christian</MenuItem>
                      <MenuItem value="muslim">Muslim</MenuItem>
                      <MenuItem value="other">Other</MenuItem>
                    </Select>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='bloodGroup' label='Blood Group' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.bloodGroup} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <FormControl className={`${styles.input} ${styles.radioInput} flex-wrap flex-row`}>
                    <FormLabel className={`${styles.radioLabel}`}>Kashmiri Immigrant:</FormLabel>
                    <RadioGroup row id="kashmiriImmigrant" name='kashmiriImmigrant' aria-label='kashmiriImmigrant' onChange={(event)=>handleInputChangeByName(event)} value={personalInfo.kashmiriImmigrant}>
                      <FormControlLabel value='1' control={<Radio />} label='Yes' />
                      <FormControlLabel value='0' control={<Radio />} label='No' />
                    </RadioGroup>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='nameInHindi' label='Name (in Hindi) (Enter words, it will be converted into Hindi.)' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.nameInHindi} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='birthPlace' label='Birth Place' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.birthPlace} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='identificationMark' label='Identification Mark' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.identificationMark} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <TextField id='hobbies' label='Hobbies' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.hobbies} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='extraCurricularActivities' label='Extra Curricular Activities' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.extraCurricularActivities} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='otherReleventInfo' label='Other Relevent Info' className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.otherReleventInfo} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Parent's Bank Details</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                <TextField id='parentsBankName' label="Parent's Bank Name" className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.parentsBankName} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='parentsAccountNo' label="Parent's Account Number" className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.parentsAccountNo} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='parentsIFSCCode' label="Parent's IFSC Code" className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.parentsIFSCCode} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='candidatesFavouritePastTime' label="Candidate's Favourite Past Time" className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.candidatesFavouritePastTime} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                <FormControl className={`${styles.input} ${styles.radioInput} flex-wrap flex-row`}>
                    <FormLabel className={`${styles.radioLabel}`}>Please Select:</FormLabel>
                    <RadioGroup row id="identityType" name='identityType' aria-label='identityType' onChange={(event)=>handleInputChangeByName(event)} value={personalInfo.identityType}>
                      <FormControlLabel value='Aadhar' control={<Radio />} label='Aadhar Number' />
                      <FormControlLabel value='Passport' control={<Radio />} label='Passport Number' />
                    </RadioGroup>
                  </FormControl>
                </div>
                <div className={`${styles.formBlock}`}>
                <TextField id='migrationCertificateNo' label="Migration Certificate Number" className={`${styles.input}`} 
                    onChange={(event)=>handleInputChange(event)}
                    value={personalInfo.migrationCertificateNo} required/>
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
    </Card>
  );
}
