import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [academicInfo, setAcademicInfo] = useState([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
  const [errorMessage, setErrorMessage] = useState('');

  const handleInputChange = (index, event) => {
    const { name, value } = event.target;
    const list = [...academicInfo];
    list[index][name] = value;
    setAcademicInfo(list);
    localStorage.setItem('academicInfo', JSON.stringify(academicInfo));
  };

  const handleAddFields = () => {
    setAcademicInfo([...academicInfo, { nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: academicInfo.length + 1 }]);
    localStorage.setItem('academicInfo', JSON.stringify(academicInfo));
  };

  const handleRemoveFields = (index) => {
    const list = [...academicInfo];
    list.splice(index, 1);
    setAcademicInfo(list);
    localStorage.setItem('academicInfo', JSON.stringify(academicInfo));
  };

  const handlePrev = () => {
    // event.preventDefault();
    // Check if all fields are filled
    // for (const info of academicInfo) {
    //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
    //     setErrorMessage('Please fill out all fields.');
    //     return;
    //   }
    // }
    // Validation passed, store data in localStorage
    localStorage.setItem('academicInfo', JSON.stringify(academicInfo));
    setErrorMessage('');
    // Reset form
    setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
    router.push('/personal');
  };

  const handleNext = () => {
    // event.preventDefault();
    // Check if all fields are filled
    // for (const info of academicInfo) {
    //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
    //     setErrorMessage('Please fill out all fields.');
    //     return;
    //   }
    // }
    // Validation passed, store data in localStorage
    localStorage.setItem('academicInfo', JSON.stringify(academicInfo));
    setErrorMessage('');
    // Reset form
    setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
    router.push('/parent-account');
  };


  return (
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}>
              <div className={`${styles.formHeader}`}>
                <h2>Education Details</h2>
                <p>Please do not use Autofill.</p>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Admission Based on:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Department:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Rank:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>ABC ID:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              {academicInfo.map((info, index) => (
                <div key={index} className={`${styles.formPart}`}>
                  <div className={`${styles.partHeading}`}>
                    <h3>Education Details</h3>
                  </div>

                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Name of Examination:</label>
                    <input type="text" id="" name="nameOfExamination" className={`${styles.input}`} value={info.nameOfExamination} onChange={(event) => handleInputChange(index, event)} required />
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>University/Board:</label>
                    <input type="text" id="" name="university_Board" className={`${styles.input}`} value={info.university_Board} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Year:</label>
                    <input type="text" id="" name="year" className={`${styles.input}`} value={info.year} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Institute/School:</label>
                    <input type="text" id="" name="institute_school" className={`${styles.input}`} value={info.institute_school} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Grade/Percentage:</label>
                    <input type="text" id="" name="grade_percentage" className={`${styles.input}`} value={info.grade_percentage} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Marksheet:</label>
                    <input type="text" id="" name="" className={`${styles.input}`} />
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Division:</label>
                    <input type="text" id="" name="division" className={`${styles.input}`} value={info.division} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Certificate:</label>
                    <input type="text" id="" name="" className={`${styles.input}`} />
                  </div>
                  <div className={`${styles.formBlock}`}>
                    <label htmlFor="" className={`${styles.label}`}>Major Subjects:</label>
                    <input type="text" id="" name="majorSubjects" className={`${styles.input}`} value={info.majorSubjects} onChange={(event) => handleInputChange(index, event)} required/>
                  </div>
                  {index > 0 && (
                    <div className={`${styles.delAcadContainer}`}>
                      <button onClick={() => handleRemoveFields(index)} className={`${styles.delAcadBtn}`}>Remove</button>
                    </div>
                  )}
                </div>
              ))}

              <div className={`${styles.addAcadContainer}`}>
                <button onClick={handleAddFields} className={`${styles.addAcadBtn}`}>Add Academic</button>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handlePrev} className={`${styles.formBtn}`}>Previous</button>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
