import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}>
              <div className={`${styles.formHeader}`}>
                <h2>Personal Details</h2>
                <p>Please do not use Autofill.</p>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Registration No:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Institute Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Email:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Contact Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Gender:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Category:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Nationality:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Divyang:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Permanent Address:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Street Locality:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>City:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>State:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Pincode:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Country:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Date of Birth:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Marital Status:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Religion:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Blood Group:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Kashmiri Immigrant:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Name (in Hindi): <br/>(Enter word and space, it will be converted into Hindi.)</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Birth Place:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Identification Mark:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Hobbies:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Extra Curricular Activities:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Other Relevent info:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Parent's Bank Details</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Bank Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Account Number: <br/> (Will also be used for Parent Portal)</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's IFSC Code:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Candidate's Favourite Past time:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Please Select:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Migration Certificate No.:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <Link href="/education" className={`${styles.formBtn}`}>Next</Link>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
