import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
    const router = useRouter();

    const handlePrev = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      router.push('/parent-account');
    };
  
    const handleNext = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      router.push('/form-preview');
    };

  return (
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}>

            <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Important Information for Hostel</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Food habit:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>If Having Laptop (Give Details):</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Model Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Serial Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Email Registraion</h3>
                  <p>(Your email will be created on IITISM Domain, adm_no@iitism.ac.in)</p>
                  <p>Your default temporary password is shown in the form. All official communication will be sent on this email only.</p>
                </div>

                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Email Username:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Email Password:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Student Account Detail</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Bank Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Account Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Confirm Account Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>IFSC Code:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handlePrev} className={`${styles.formBtn}`}>Previous</button>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
