import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
    const router = useRouter();

    const handlePrev = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      router.push('/education');
    };
  
    const handleNext = () => {
      // event.preventDefault();
      // Check if all fields are filled
      // for (const info of academicInfo) {
      //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
      //     setErrorMessage('Please fill out all fields.');
      //     return;
      //   }
      // }
      // Validation passed, store data in localStorage
    //   localStorage.setItem('academicInfo', academicInfo);
    //   setErrorMessage('');
    //   // Reset form
    //   setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
      router.push('/other');
    };

  return (
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}>
              <div className={`${styles.formHeader}`}>
                <h2>Parent Account Details</h2>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Father's Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Mother's Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Father's Occupation:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Mother's Occupation:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Father's Income (Annually):</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Mother's Income (Annually):</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Mobile Number: <br/> (Cannot be changed and also used in Parent Portal)</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Email id:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Guardian's Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Guardian's Relation:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Alternate mobile No::</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Alternate Email id:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handlePrev} className={`${styles.formBtn}`}>Previous</button>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
