import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleNext = () => {
    // event.preventDefault();
    // Check if all fields are filled
    // for (const info of academicInfo) {
    //   if (!info.schoolName || !info.educationLevel || !info.graduationYear) {
    //     setErrorMessage('Please fill out all fields.');
    //     return;
    //   }
    // }
    // Validation passed, store data in localStorage
    // localStorage.setItem('academicInfo', academicInfo);
    // setErrorMessage('');
    // // Reset form
    // setAcademicInfo([{ nameOfExamination: '', university_Board: '', year: '', institute_school: '', grade_percentage: '', division: '', majorSubjects: '', id: 1 }]);
    router.push('/education');
  };

  return (
    <>
      <Head>
        <title>Ph.D Admission (Externally Funded)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.container}`}>
          <div className={`${styles.formNavBar}`}>

          </div>
          <div className={`${styles.formContainer}`}>
            <form className={`${styles.formBody}`}>
              <div className={`${styles.formHeader}`}>
                <h2>Personal Details</h2>
                <p>Please do not use Autofill.</p>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Registration No:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Institute Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Email:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Contact Number:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Gender:</label>
                  <div className={`${styles.input} ${styles.radioInput}`}>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="gender_male" name="gender" value="male" />
                      <label htmlFor="gender_male">Male</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="gender_female" name="gender" value="female" />
                      <label htmlFor="gender_female">Female</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="gender_transgender" name="gender" value="transgender" />
                      <label htmlFor="gender_transgender">Transgender</label>
                    </div>
                  </div>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Category:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Nationality:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Divyang:</label>
                  <div className={`${styles.input} ${styles.radioInput}`}>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="Divyang_yes" name="divyang" value="yes" />
                      <label htmlFor="Divyang_yes">Yes</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="Divyang_no" name="divyang" value="no" />
                      <label htmlFor="Divyang_no">No</label>
                    </div>
                  </div>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Permanent Address:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Street/Locality:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>City:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>State:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Pincode:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Country:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Date of Birth:</label>
                  <input type="date" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Marital Status:</label>
                  <div className={`${styles.input} ${styles.radioInput}`}>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="MS_married" name="maritalStatus" value="married" />
                      <label htmlFor="MS_married">Married</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="MS_unmarried" name="maritalStatus" value="unmarried" />
                      <label htmlFor="MS_unmarried">Unmarried</label>
                    </div>
                  </div>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Religion:</label>
                  <select defaultValue={'none'} name="religion" id="religion" className={`${styles.input} ${styles.dropdown}`}>
                    <option value="none" disabled> -- select an option -- </option>
                    <option value="hindu">Hindu</option>
                    <option value="sikh">Sikh</option>
                    <option value="christian">Christian</option>
                    <option value="muslim">Muslim</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Blood Group:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Kashmiri Immigrant:</label>
                  <div className={`${styles.input} ${styles.radioInput}`}>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="KI_yes" name="kashmiriImmigrant" value="yes" />
                      <label htmlFor="KI_yes">Yes</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="KI_no" name="kashmiriImmigrant" value="no" />
                      <label htmlFor="KI_no">No</label>
                    </div>
                  </div>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Name (in Hindi): <br/>(Enter word and space, it will be converted into Hindi.)</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Birth Place:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Identification Mark:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Hobbies:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Extra Curricular Activities:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Other Relevent info:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formPart}`}>
                <div className={`${styles.partHeading}`}>
                  <h3>Parent's Bank Details</h3>
                </div>

                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Bank Name:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's Account Number: <br/> (Will also be used for Parent Portal)</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Parent's IFSC Code:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Candidate's Favourite Past time:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Please Select:</label>
                  <div className={`${styles.input} ${styles.radioInput}`}>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="identify_aadhar" name="identify" value="aadhar" />
                      <label htmlFor="identify_aadhar">Aadhar Number</label>
                    </div>
                    <div className={`${styles.radioOption}`}>
                      <input type="radio" id="identify_passport" name="identify" value="passport" />
                      <label htmlFor="identify_passport">Passport Number</label>
                    </div>
                  </div>
                </div>
                <div className={`${styles.formBlock}`}>
                  <label htmlFor="" className={`${styles.label}`}>Migration Certificate No.:</label>
                  <input type="text" id="" name="" className={`${styles.input}`} required/>
                </div>
              </div>

              <div className={`${styles.formFooter}`}>
                <button onClick={handleNext} className={`${styles.formBtn}`}>Next</button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
